### ISSUE TITLE
Add YAML section `definitions.common` that merges its content with all indicators

### ISSUE THREAD

**Issue by Marigold** [owid/etl#1733]
Contents of section `definitions.common` in YAML should be merged with all indicators.

Some ideas:

1.  I suppose common could have as many inputs as indicator metadata fields. I was wondering if we may want a common for each table...
```yaml
definitions:
  common:
    global_emissions: [the name of one table]
      description_key: [common description key for all indicators in the table]
    land_use_emissions: [another table]
      description_key: [common description key for all indicators in the table]
...
```

2. Would be nice if we could choose between two behaviours: (1) anything in commons is propagated to indicators’ fields, or (2) it is appended to the indicators fields’ content (e.g. string fields are added at the end, description_key bullet points are added to those already present, etc.)

3. It would be super cool if we could somehow choose to which indicators the definitions apply. It is nice that by default they apply to all of the indicators, but maybe sometimes we want to apply them to a subset of the indicators.
