### ISSUE TITLE
Move ETL buildkite pipelines into the repo

### ISSUE THREAD

**Issue by larsyencken** [owid/etl#2124]
## Background

For Github CI jobs, you keep the workflows in `.github/` in the repo. For Buildkite, we have many workflows, but we haven't put them in the repo to be triggered.

## Getting it working

Let's say we have a pipeline `<pipeline>`. 

1. Make a file`.buildkite/<pipeline>.yaml` with the pipeline you want to run
2. Update the YAML step in the Buildkite admin to something like this

```yaml
steps:
  - command: "buildkite-agent pipeline upload .buildkite/<pipeline>.yml"
    label: "Upload pipeline"
```

## Technical notes

- If we roll this out at once, all the existing branches will skip CI checks since they will have no pipelines yet
  - We may want to add `.buildkite/<pipeline>.yml` files in advance, then turn it on later
- Serving the pipeline from the repo has the pro & con that the branch gets to define its own CI job
  - So we lose the ability to do a global switch between CI jobs
  - ❓ Can we always use the YAML file from the `master` branch, no matter what branch we're doing CI on?
