### ISSUE TITLE
wizard: make apps more modular

### ISSUE THREAD

**Issue by lucasrodes** [owid/etl#2255]
Currently, it is not obvious how to integrate a new app into Wizard. In particular, we have hard-coded strings in both `apps/wizard/home.py` and `apps/wizard/app.py`.

We should instead have a single configuration YAML file which lists the different apps. It also should have some minor guidelines on how to add new apps to Wizard.

**Comment by lucasrodes** [comment]
Currently thinking of a YAML file `apps/wizard/config.yml` where you can add a section with apps as follows:

```yaml
sections:
  - title: "Charts"
    description: |-
      Create chart revisions, and synchronize aproved revisions between servers.
    apps:
      - title: "Chart revision baker"
        alias: charts
        entrypoint: charts/__main__.py
        description: Prepare chart revisions.
        maintainer: "@lucas"
        emoji: "🧑‍🍳"
        image_url: "https://camo.githubusercontent.com/38a295d2c16cd880446f874a786e94fb168d6aadfdcbc4c8b7dd45c8337b6d1d/68747470733a2f2f6f7572776f726c64696e646174612e6f72672f677261706865722f6578706f7274732f6c6966652d657870656374616e63792e737667"
```

In the example below, we add a section "Charts" with a single app "Chart revision baker". Each app should have a title, an alias, an entry point (streamlet script), a description, emoji and an image URL (an image that represents the app's functionality).

**Comment by lucasrodes** [comment]
We notice that there are some "special" sections: those that help build etl steps. These require a different treatment in Wizard, and their UI layout is slightly more custom. Therefore, we force users to have them defined. Instead of them living under the `sections` property, they live in `etl` property.


```
etl:
  title: ETL steps
  description: Create an ETL step.
  steps:
    snapshot:
      title: "Snapshot"
      alias: snapshot
      entrypoint: etl_steps/snapshot.py
      emoji: "1️⃣"
      image_url: "https://cdn.pixabay.com/photo/2014/10/16/09/15/lens-490806_1280.jpg"
    meadow:
      title: "Meadow"
      alias: meadow
      entrypoint: etl_steps/meadow.py
      emoji: "2️⃣"
      image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Blumenwiese_bei_Obermaiselstein05.jpg/1024px-Blumenwiese_bei_Obermaiselstein05.jpg"
    garden:
      title: "Garden"
      alias: garden
      entrypoint: etl_steps/garden.py
      emoji: "3️⃣"
      image_url: "https://upload.wikimedia.org/wikipedia/commons/2/27/Butchart_gardens.JPG"
    grapher:
      title: "Grapher"
      alias: grapher
      entrypoint: etl_steps/grapher.py
      emoji: "4️⃣"
      image_url: "https://pbs.twimg.com/media/EbHwdjwUcAEfen4?format=jpg&name=large"
    fasttrack:
      title: "Fast Track"
      alias: fasttrack
      entrypoint: etl_steps/fasttrack.py
      emoji: "🏎️"
      image_url: "https://upload.wikimedia.org/wikipedia/commons/b/be/Alonso_%28Renault%29_qualifying_at_USGP_2005.jpg"
```
