### ISSUE TITLE
Preferred way to cite WDI and PIP indicators

### ISSUE THREAD

**Issue by pabloarosado** [owid/etl#3971]
WDI people contacted us and suggested a very specific way to cite their data (which seems to also apply to PIP). This is what they proposed:

[...] we wanted to give you some feedback on how we would like our WDI and PIP data to be cited. Please see our suggestions below.
 
Short citation (please include):
1. Name of database like World Development Indicators or Poverty and Inequality Platform
2. Name of organization: World bank
3. Indicator codes: this is optional if hyperlink included specifically to the indicator
4. Hyperlink(s) to the indicator page on the world bank data site ([data.worldbank.org](http://data.worldbank.org/)) or PIP platform. Please include links to all indicators if using more than one indicator.
 
Long citation (please include):
1. Name of database like World Development Indicators or Poverty and Inequality Platform
2. Name of organization: World bank
3. Indicator codes
4. Date of data retrieval
5. Source of data for WDI (not applicable for PIP). By this, we mean, if the indicator is "population using internet" which comes from ITU, you should also mention ITU.
6. Hyperlink(s) to the indicator page on the world bank data site ([data.worldbank.org](http://data.worldbank.org/)) or PIP platform. Please include links to all indicators if using more than one indicator.

It's great that they defined very specific guidelines. We need to figure out the best way to adjust our current WDI (and PIP?) pipeline, with our current metadata schema, to their requirements.

**Comment by lucasrodes** [comment]
I wonder how these recommendations affect the chart source footer.

In there, we are limited with space, so ideally it shouldn't be very long.

Also, their suggestion seems to point to something similar to what we had in the past (cite WB but not original source in the footer). 

My understanding is that we were moving away from that, though this is revisable ofc.

My preference is for adding original source with a reference to WB, e.g.:

```

International Telecommunication Union (2025), via World Bank
```

**Comment by Marigold** [comment]
I started looking into this a bit. I'll post a couple of examples here to have something concrete. You may find the [dummy data page](https://admin.owid.io/admin/datapage-preview/810767) useful for seeing where origin's attributes end up.

WDI metadata contains "Source". It can be a bit long sometimes, and we are currently shortening it to fit it into footer. Some examples of their sources (full list is [here](https://github.com/owid/etl/blob/master/etl/steps/data/garden/worldbank_wdi/2025-01-24/wdi.sources.json)):
- `Food and Agriculture Organization, electronic files and web site.`
- `(1) United Nations Population Division. World Population Prospects: 2024 Revision; (2) Statistical databases and publications from national statistical offices; (3) Eurostat: Demographic Statistics; (4) United Nations Statistics Division. Population and Vital Statistics Report (various years).`
- `Development Assistance Committee of the Organisation for Economic Co-operation and Development, Geographical Distribution of Financial Flows to Developing Countries, Development Co-operation Report, and International Development Statistics database. Data are available online at: www.oecd.org/dac/stats/idsonline. IMF central government expense estimates are used for the denominator.`
- `Netcraft (http://www.netcraft.com/) and World Bank population estimates.`
- `United Nations Conference on Trade and Development, Handbook of Statistics and data files, and International Monetary Fund, International Financial Statistics.`

I picked two examples. One is `Food and Agriculture Organization, electronic files and web site.`. I propose to define origin like this:
```
origin:
  producer: Food and Agriculture Organization of the United Nations
  title: World Development Indicators (World Bank)
  description: |-
    The World Development Indicators (WDI) is the primary World Bank collection of development indicators, compiled from officially-recognized international sources. It presents the most current and accurate global development data available, and includes national, regional and global estimates.
  url_main: https://data.worldbank.org/indicator/AG.CON.FERT.PT.ZS
  citation_full: {rawName}. Indicator AG.CON.FERT.PT.ZS ({url_main}), {title} ({date_published})
  attribution: None
```

Note that:
- Chart footer doesn't reference World Bank or WDI, but only upstream producer. If that's a problem, we can concatenate it with `World Development Indicators (World Bank)`
- `description` is always the same for all indicators
- `producer` is shortened from raw source name using LLM

Another example is `International Telecommunication Union (ITU) World Telecommunication/ICT Indicators Database`
```
origin:
  producer: International Telecommunication Union (ITU)
  title: World Development Indicators (World Bank)
  description: |-
    The World Development Indicators (WDI) is the primary World Bank collection of development indicators, compiled from officially-recognized international sources. It presents the most current and accurate global development data available, and includes national, regional and global estimates.
  url_main: https://data.worldbank.org/indicator/IT.NET.USER.ZS
  citation_full: {rawName}. Indicator IT.NET.USER.ZS ({url_main}), {title} ({date_published})
  attribution: None
```

If you think this is a good start, I can create a PR with the proposal and we can incrementally improve it.
