### ISSUE TITLE
MDIMs: More prominent dimensions

### ISSUE THREAD

**Issue by Marigold** [owid/etl#4007]
## Motivation

We're somehow arbitrarily switching between dimensional data (sometimes called "long" format) and flattened data ("wide" format). This flattening of dimensional data happens at the end of the `data://grapher` step and converts e.g.
```
Ambient air pollution attributable death rate (per 100 000 population)
```
with dimensions
```
{"sex": "both_sexes", "age_group": "70-74 years", "cause": "stroke"}
```
into an indicator
```
Ambient air pollution attributable death rate (per 100 000 population) - Sex: both sexes - Age group: 70-74 years - Cause: Stroke
```
with short name constructed from dimension names and values
```
ambient_air_pollution_attributable_death_rate__per_100_000_population__sex_both_sexes__age_group_70_74_years__cause_stroke
```

Since dimensions can't be easily reconstructed from the name, we also save the info about dimensions into `tb[col].m.additional_info` as
```json
{
  "dimensions": {
     "originalShortName": "ambient_air_pollution_attributable_death_rate__per_100_000_population", 
      "originalName": "Ambient air pollution attributable death rate (per 100 000 population)",
         "filters": [
             {"name": "sex", "value": "both sexes"},
             {"name": "age_group", "value": "70-74 years"},
             {"name": "cause", "value": "Stroke"},
         ],
   }
}
```

This info about dimensions is handy when creating mdim configs or as a way to trace it back to the original dimensional dataset.

## Problem

We're having constant discussions about whether we should work with dimensional or flattened data. Both have pros and cons - some prefer to use dimensional form with Jinja templating for metadata, some prefer to flatten programmatically and create metadata in pure python. I think supporting both doesn't create much additional effort, but we should make sure to **include information about dimensions** when doing so. That'd make our work with mdims and explorers much easier.

One example where this was a problem were [energy prices](https://github.com/owid/etl/blob/master/etl/steps/export/multidim/energy/latest/energy_prices.py). It creates views using [generate_views_for_dimensions](https://github.com/owid/etl/blob/master/etl/multidim.py#L842) that assumes short names have dimensions separated by `_`. If we had dimensions info, we could use a more generic `expand_views` function.

Another thing is where and how we store dimension info. It was created hastily a few years ago as an experiment and put in `additional_info` attribute. It could have its own prominent field (e.g. `tb[col].metadata.dims`) and be defined as a dictionary. It should contain enough information for converting flattened format back to dimensional.

**Comment by Marigold** [comment]
Good feedback! The last point got me thinking more concretely about the proposal. Here's something half-baked. In garden YAML we could add info about dimensions as

```yaml
tables:
  cherry_blossom:
    # on table level
    dimensions:
      - name: Sex
        slug / short_name: sex
        description: ...
      - name: Age group
        slug: age_group
        description: ...

    # dimension values are specified per indicator
    variables:
      ambient_air_pollution_attributable_death_rate__per_100_000_population:
        dims:
          sex: Male
          age_group: 70-74 years
          cause: Stroke
```

@pabloarosado often flattens in the garden step (like [here](https://github.com/owid/etl/blob/b74238244647b831baf6670c9b5924e5a182d18e/etl/steps/data/garden/eurostat/2024-11-05/gas_and_electricity_prices.meta.yml#L105)) and this could be a convenient way how to add this info into metadata.

Dimensional datasets would have it filled for indicators automatically, but it'd still be useful to define dimensions "metadata" (names, descriptions) on the table level.
