### ISSUE TITLE
Autoupdate improvements

### ISSUE THREAD

**Issue by Marigold** [owid/etl#4353]
Snapshots with `autoupdate` block in `*.dvc` are autoupdated. The block looks like this
```
autoupdate:
  name: My Update
  frequency: monthly
  notify: my-slack-name
```

Here are some ideas for future improvements (if autoupdates get used enough)

- [ ] Add it to ETL docs
- [ ] Implement `frequency` and `notify` for autoupdates
- [ ] owidbot should post a link to `chart-diff` with query parameter `?show_all=` to show all charts by default
- [ ] Keep track of changes via `history:` in the DVC yaml file
- [ ] Auto-assign owners (need to specify that in the `autoupdate:` block, perhaps having `owner` instead of `notify` would be more appropriate?)
