### ISSUE TITLE
Save DVC remote when pushing the file to S3

### ISSUE THREAD

**Issue by Marigold** [owid/etl#810]
Running `dvc push ...` now generates the following section in `*.xlsx.dvc`

```yaml
outs:
- md5: 0fadb25212dd37be38cd098899873a35
  size: 1764793
  path: ggdc_maddison.xlsx
```

Running `dvc push ... -r myremote` doesn't add `remote: myremote` field to YAML (no idea why not). If we add it ourselves, we would be pushing to the correct remote even if we forget to set `-r myremote` (and accidentally push private data to a public bucket).
